name: Atul_Test2
description: ''
version: ver1
author: atulanand.2010@gmail.com
language: python
buildSystem: ''
buildSystemDetails:
  artefactID: atultest2
  parentArtefactID: atulanand2010gmailcomteam
  buildSystem: wheel
  author: null
  createdAt: '2024-06-04 15:34:46'
pipelines:
  pipelines/enrich_accounts:
    name: enrich_accounts
    description: ''
    author: atulanand.2010@gmail.com
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2024-06-04 15:34:46'
    datasets:
      inputs:
      - gitUri=http://gitserver:3000/wvwrv9bI_team_5938/wvwrv9bI_project_13587.git&subPath=&tag=course_lab_sources/0.0.3&projectSubscriptionProjectId=13587&path=datasets/salesforce-Account
      - gitUri=http://gitserver:3000/wvwrv9bI_team_5938/wvwrv9bI_project_13587.git&subPath=&tag=course_lab_sources/0.0.3&projectSubscriptionProjectId=13587&path=datasets/salesforce-Opportunity
      outputs:
      - datasets/enriched_accounts
    subgraphs: []
    dependencies: {}
datasets:
  datasets/enriched_accounts:
    name: enriched_accounts
    description: ''
    author: atulanand.2010@gmail.com
    createdAt: '2024-06-04 16:03:57'
    mode: batch
    physicalDatasets:
      workshop-fabric:
        fabricId: 13159
        datasetType: Database
        description: ''
        author: atulanand.2010@gmail.com
        createdAt: '2024-06-04 16:03:57'
templates: {}
jobs: {}
gemContainer:
  languageVersion: '3.10'
  gemLibsVersion: 1.3.4.0
  gems: {}
  dependencies: null
functions:
  author: null
  createdAt: '2024-06-04 15:34:46'
  udfs: {}
  udafs: {}
  expressions: {}
  airflowFunctions: {}
subgraphs: {}
sqlModels: {}
sqlSnapshots: {}
sqlTests: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline: null
dependencies:
- modifiedAt: '2024-06-04T15:34:46.712996Z'
  name: plibMaven
  version: 7.1.102
  id: '856448051'
  createdAt: '2024-06-04T15:34:46.712996Z'
  type: plibMaven
- modifiedAt: '2024-06-04T15:34:46.712996Z'
  name: plibPypi
  version: 1.8.19
  id: '174856929'
  createdAt: '2024-06-04T15:34:46.712996Z'
  type: plibPypi
projectDependencies:
  '12654':
    projectUID: 12654
    projectName: ProphecySparkBasicsPython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12654.git&subPath=
    version: 0.2.14
    isDefault: true
    author: null
    createdAt: '2024-06-04 15:34:18'
  '13587':
    projectUID: 13587
    projectName: course_lab_sources
    repositoryPath: gitUri=http://gitserver:3000/wvwrv9bI_team_5938/wvwrv9bI_project_13587.git&subPath=
    version: course_lab_sources/0.0.3
    isDefault: false
    author: null
    createdAt: '2024-06-04 15:34:18'
  '12655':
    projectUID: 12655
    projectName: ProphecyWarehousePython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12655.git&subPath=
    version: 0.0.6
    isDefault: true
    author: null
    createdAt: '2024-06-04 15:34:18'
flags:
  shouldAddDefaultDependenciesIfAbsent: true
pipelineConfigurations: {}
